name: Quay CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1'
    - run: go version
    - run: go build cmd/main.go
    - name: Get quay(openebs namespace) data
      run: |
        echo "Starting to get openebs quay data"
        ./main --quay-auth-token=${{ secrets.QUAY_AUTH_TOKEN }} --quay-namespace=openebs
        echo "Finished getting logs"
    - name: Calculating sizes of `logs` directory
    # SIZE will be in Kilobytes (K); When nothing is downloaded, size is around 4K
      run: |
        SIZE=$(eval "du -shk logs")
        echo $SIZE
        read size dirname <<< $SIZE
        echo $size
        echo $dirname
        echo "Finish Calculating size"
        echo "::set-env name=LOGS_DIR_SIZE::$size"
    - name: Displaying Directory size
      run: |
        echo $LOGS_DIR_SIZE;
        echo "displaying Logs Directory size"
    - name: Send mail
      if: $LOGS_DIR_SIZE < 10
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Quay Logs less files error
        # Literal body:
        body: Quay logs data of ${{github.repository}} is less than 10K, looks like something is wrong
        to: amrishindia62@gmail.com
        from: Growth Metrics # <user@example.com>
    # - name: Install binary of minio client
    #   run: |
    #     wget https://dl.min.io/client/mc/release/linux-amd64/mc
    #     chmod +x mc
    #     ./mc --help
    # - name: Config mc (minio client)
    #   run: |
    #     ./mc --help
    #     ./mc config host add s3 ${{ secrets.AWS_HOSTNAME }} ${{ secrets.AWS_ACCESS_KEY }} ${{ secrets.AWS_SECRET_KEY }}
    # - name: Copy logs data to amazon-s3
    #   run: |
    #     ./mc ls s3
    #     echo "Start coping"
    #     ./mc cp "logs" s3/quay-openebs-metrics/ --recursive
    #     echo "Coping successful"